# Generated by Django 5.2.8 on 2025-11-19 01:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Vault ID')),
                ('name', models.CharField(max_length=200, verbose_name='Vault name')),
                ('api_key', models.CharField(max_length=64, verbose_name='API key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this vault active?')),
                ('created_utc_s', models.BigIntegerField(default=1763516030.3415391, verbose_name='Unix timestamp for when the Vault was created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='API key')),
                ('created_utc_s', models.BigIntegerField(default=1763516030.3457742, verbose_name='Unix timestamp for when the Vault was created')),
                ('expiration_utc_s', models.BigIntegerField(default=1763516030.345779, verbose_name='Unix timestamp for expiration time in seconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaults')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Action ID')),
                ('type', models.CharField(max_length=20, verbose_name='Action type')),
                ('status', models.CharField(max_length=20, verbose_name='Status of the action')),
                ('path', models.CharField(max_length=300, verbose_name='ath to the file in the vault')),
                ('created_utc_s', models.BigIntegerField(default=1763516030.345928, verbose_name='Unix timestamp for when the Action was created')),
                ('completed_utc_s', models.BigIntegerField(default=1763516030.345931, verbose_name='Unix timestamp for when the Action was completed by the client')),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vaults')),
            ],
        ),
    ]
