# Generated by Django 5.2.8 on 2025-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='completed_utc_s',
            field=models.BigIntegerField(default=1763516050.233685, verbose_name='Unix timestamp for when the Action was completed by the client'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='created_utc_s',
            field=models.BigIntegerField(default=1763516050.233682, verbose_name='Unix timestamp for when the Action was created'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='created_utc_s',
            field=models.BigIntegerField(default=1763516050.233524, verbose_name='Oh shit I messed up timestamp for when the Vault was created'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='expiration_utc_s',
            field=models.BigIntegerField(default=1763516050.233529, verbose_name='Unix timestamp for expiration time in seconds'),
        ),
        migrations.AlterField(
            model_name='vaults',
            name='created_utc_s',
            field=models.BigIntegerField(default=1763516050.229494, verbose_name='Unix timestamp for when the Vault was created'),
        ),
    ]
