# Generated by Django 5.2.8 on 2025-11-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_actions_completed_utc_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='completed_utc_s',
            field=models.BigIntegerField(default=1763516068.348922, verbose_name='Unix timestamp for when the Action was completed by the client'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='created_utc_s',
            field=models.BigIntegerField(default=1763516068.3489192, verbose_name='Unix timestamp for when the Action was created'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='created_utc_s',
            field=models.BigIntegerField(default=1763516068.348764, verbose_name='Unix timestamp for when the Vault was created'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='expiration_utc_s',
            field=models.BigIntegerField(default=1763516068.348769, verbose_name='Unix timestamp for expiration time in seconds'),
        ),
        migrations.AlterField(
            model_name='vaults',
            name='created_utc_s',
            field=models.BigIntegerField(default=1763516068.344766, verbose_name='Unix timestamp for when the Vault was created'),
        ),
    ]
