# Generated by Django 5.2.8 on 2025-11-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_actions_completed_utc_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='completed_utc_s',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/time when the Action was completed by the client'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='created_utc_s',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/time when the Action was created'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='created_utc_s',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/time for when the API key was created'),
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='expiration_utc_s',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/time for expiration time in seconds'),
        ),
        migrations.AlterField(
            model_name='vaults',
            name='created_utc_s',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/time for when the Vault was created'),
        ),
    ]
