# Generated by Django 5.2.8 on 2025-11-20 00:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_actions_completed_utc_s_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actions',
            new_name='Action',
        ),
        migrations.RenameModel(
            old_name='ApiKeys',
            new_name='ApiKey',
        ),
        migrations.RenameModel(
            old_name='Vaults',
            new_name='Vault',
        ),
    ]
