# Generated by Django 5.2.8 on 2025-11-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_actions_action_rename_apikeys_apikey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='path',
            field=models.CharField(max_length=300, verbose_name='Path to the file in the vault'),
        ),
    ]
