# Generated by Django 5.2.8 on 2025-11-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_action_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='api_key',
        ),
    ]
