# Generated by Django 5.2.8 on 2025-11-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_vault_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
    ]
